### PR TITLE
feat: add left border option for sections

### LINKED ISSUE #96: Content Break and Left Border apply to whole section not columns block
See https://www.stewart.com/en/what-we-offer/insurance.html

image

### PR DESCRIPTION
**Pull request by usman-khalid**
Fix #96 

Test URLs:
- Before: https://main--stewart--hlxsites.hlx.page/en/what-we-offer/insurance
- After: https://feature-section-left-border--stewart--hlxsites.hlx.page/en/what-we-offer/insurance

Block library updated: https://feature-section-left-border--stewart--hlxsites.hlx.page/library/blocks/section-backgrounds

### CODE REVIEW

**Comment by shsteimer** [comment]
@usman-khalid check the home page as well. needs to handle the scenario where the content in the section is a cols block, not default content. Also note that in the importer I renamed the style banner to match their current content.

**Comment by usman-khalid** [comment]
> @usman-khalid check the home page as well. needs to handle the scenario where the content in the section is a cols block, not default content. Also note that in the importer I renamed the style banner to match their current content.

@shsteimer the left border option exists on the column block to achieve that — updated the content on the homepage: https://feature-section-left-border--stewart--hlxsites.hlx.page/en

**Comment by shsteimer** [comment]
I'm not sure I have a strong answer for this, but my primary concern here is what is easiest for authors. My thinking was that for authors, it's always a section style. if that section just has default content, then the left border applies to that, if it has columns, then it applies to the first column. I think it's odd to say that it is sometimes a block variant, and sometimes a section style.

Maybe the right answer is actually that is should *always* be a block variant, and we should change the importer to convert the instances when it's default content into a block that uses that variant?

**Comment by shsteimer** [comment]
oh, also regarding the naming. I had originally called this left border, but if you look at their current markup, they call it banner, so was thinking to rename to that for consistency (and ideally something their authors are already familiar with terminology wise)

**Pull request merged**
